name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Test
        run: ls -la && ls / && ls app && ls app/build && ls app/build/outputs && ls app/build/outputs/apk && ls app/build/outputs/apk/release
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: TaigaMobile-1.5.2.apk
          path: app/build/outputs/apk/release/TaigaMobile-1.5.2.apk
        
